[package]
name = "engine_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frosty_alloc = { path = "../frosty_alloc" }
render = { path = "../render" }
hashbrown = { workspace = true }
uuid = { version = "*", features = ["v4"] }
pollster = "*"

[features]
no-app = []
no-system = []
